### ISSUE TITLE
Theme Catpuccin not found

### ISSUE THREAD

**Issue by AA1999** [rajasegar/alacritty-themes#115]
```
[arshia@arshia-pc alacritty]$ cd
[arshia@arshia-pc ~]$ alacritty-themes Catppucin
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/alacritty-themes/themes/Catppucin.yml'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at updateThemeWithFile (/usr/lib/node_modules/alacritty-themes/index.js:68:24)
    at updateTheme (/usr/lib/node_modules/alacritty-themes/index.js:117:10)
    at /usr/lib/node_modules/alacritty-themes/index.js:124:12 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/usr/lib/node_modules/alacritty-themes/themes/Catppucin.yml'
}
```

Using it the normal way:

```
[arshia@arshia-pc ~]$ alacritty-themes
? Select a theme ›
❯   3024.dark
    3024.light
    Afterglow
    Argonaut
    Ashes.dark
    Ashes.light
    Astromouse
    Atelierdune.dark
    Atelierdune.light
  ↓ Atelierforest.dark/usr/lib/node_modules/alacritty-themes/index.js:79
    (i) => i.key.value === 'colors'
                 ^

TypeError: Cannot read properties of null (reading 'value')
    at /usr/lib/node_modules/alacritty-themes/index.js:79:18
    at Array.find (<anonymous>)
    at updateThemeWithFile (/usr/lib/node_modules/alacritty-themes/index.js:78:55)
    at updateTheme (/usr/lib/node_modules/alacritty-themes/index.js:117:10)
    at /usr/lib/node_modules/alacritty-themes/index.js:124:12
```

**Comment by AA1999** [comment]
OK so the fist one was a typo but still get error on the second one.
I deleted the alacritty.yml file and managed to get it working
