### ISSUE TITLE
Error after pressing control + c

### ISSUE THREAD

**Issue by Bryan9995** [rajasegar/alacritty-themes#248]
### To Reproduce

pressed control c in terminal

1. Installation

- [X] I run it via npx alacritty-themes
- [ ] I installed it via npm i -g alacritty-themes (global installation)

2. Run alacritty-themes

- [ ] Did you add params? yes, I type "alacritty-themes Ayu-Dark"
- [X] Did you add params? no, I just type "alacritty-themes" then click up/down keys

3. See error

### Expected behavior

Somehow broke it pressing control + c. I get this error: 
backup file was created: /home/brett/.config/alacritty/alacritty.yml.1683059351612.bak
/usr/local/lib/node_modules/alacritty-themes/node_modules/yaml/dist/Document-9b4560a1.js:676
    if (this.errors.length > 0) throw new Error('Document with errors cannot be stringified');
                                      ^

Error: Document with errors cannot be stringified
    at Document.toString (/usr/local/lib/node_modules/alacritty-themes/node_modules/yaml/dist/Document-9b4560a1.js:676:39)
    at String (<anonymous>)
    at updateThemeWithFile (/usr/local/lib/node_modules/alacritty-themes/index.js:98:22)
    at updateTheme (/usr/local/lib/node_modules/alacritty-themes/index.js:117:10)
    at /usr/local/lib/node_modules/alacritty-themes/index.js:124:12

### Operating System:

- [ ] Windows
- [ ] Ubuntu
- [ ] Pop Os
- [ ] Arch
- [X] Fedora KDE 36

### Add your alacritty.yml content

```yml
# your alacritty content here
![error](https://user-images.githubusercontent.com/63263447/235779633-0bd1f7af-8957-4eaf-8d34-cf68ad990997.png)

```

### Screenshots

Add screenshots to help explain your problem.

**Comment by Bryan9995** [comment]
Is there a way just to uninstall alacritty themes and then reinstall it? It also broke on my laptop.

**Comment by Bryan9995** [comment]
I managed to get my theme back. But i still seem to receive this error.
