### ISSUE TITLE
alacriity-thems stopped working since TOML config

### ISSUE THREAD

**Issue by Neo-29** [rajasegar/alacritty-themes#261]
### To Reproduce

use alacritty-themes

3. See error

```no matches found/usr/lib/node_modules/alacritty-themes/src/helpers/index.js:6
const NoAlacrittyFileFoundError = new Error(
                                  ^

Error: No Alacritty configuration file found.
Expected one of the following files to exist:
/home/neo29/.config/alacritty/alacritty.yml
/home/neo29/.alacritty.yml
Or you can create a new one using `alacritty-themes --create`
    at Object.<anonymous> (/usr/lib/node_modules/alacritty-themes/src/helpers/index.js:6:35)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/usr/lib/node_modules/alacritty-themes/bin/cli.js:12:5)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10) ```



### Expected behavior

usual behaviour with choices

A clear and concise description of what you expected to happen.

### Operating System:

- [ ] Windows
- [ ] Ubuntu
- [ ] Pop Os
- [X] Arch gnome on wayland
- [ ] Other, which one?

### Add your alacritty.yml content

```window]
decorations = "None"
opacity = 0.85

[font]
size = 10

[cursor]
style = { blinking = "Always" }

[colors.primary]
background = "#20201d"
foreground = "#a6a28c"

[colors.cursor]
text   = "#20201d"
cursor = "#a6a28c"

[colors.normal]
black   = "#20201d"
red     = "#d73737"
green   = "#60ac39"
yellow  = "#cfb017"
blue    = "#6684e1"
magenta = "#b854d4"
cyan    = "#1fad83"
white   = "#a6a28c"

[colors.bright]
black   =  "#7d7a68"
red     =  "#d73737"
green   =  "#60ac39"
yellow  =  "#cfb017"
blue    =  "#6684e1"
magenta =  "#b854d4"
cyan    =  "#1fad83"
white   =  "#fefbec"
```
warning new toml config

### Screenshots

Add screenshots to help explain your problem.

**Comment by emilBeBri** [comment]
I get this too, of course - everyone with the newest version will.

**Comment by wcheek** [comment]
Still waiting for this.. Note that the [official installation instructions](https://github.com/alacritty/alacritty?tab=readme-ov-file#configuration) and [configuration documentation](https://alacritty.org/config-alacritty.html) tell people to use the new `TOML` configuration file... so you're losing a lot of potential users with this lack of support.

**Comment by emilBeBri** [comment]
> Still waiting for this.. Note that the [official installation instructions](https://github.com/alacritty/alacritty?tab=readme-ov-file#configuration) and [configuration documentation](https://alacritty.org/config-alacritty.html) tell people to use the new `TOML` configuration file... so you're losing a lot of potential users with this lack of support.

What do you mean " waiting for this"?  You can install it manually in 5 minutes.

**Comment by wcheek** [comment]
@emilBeBri Of course it's what I ended up doing after `alacritty-themes` didn't work. Just trying to be helpful to let developers know this issue breaks this project for anybody following the latest setup documentation - and that it's been over three months since the issue was noticed.

**Comment by emilBeBri** [comment]
@wcheek ok that makes sense.

**Comment by rajasegar** [comment]
I made a new release v6.0.0 in npm, please check and let me know or any issues

**Comment by wcheek** [comment]
@rajasegar So fast. 

It looks like it works now. There are a few issues I see. 

### First problem

Before replacing my entire custom config file the `TOML` parser threw an error about one of my keybindings:

```cmd
C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\toml-parser.js:17
  const terr = new TomlError(err.message)
               ^

TomlError: Control characters (codes < 0x1f and 0x7f) are not allowed in strings, use \u007f instead at row 320, col 16, pos 4793:
319: [[keyboard.bindings]]
      at TOMLParser.parseBasicString (C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\toml-parser.js:670:22)
      at TOMLParser.runOne (C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\parser.js:64:30)
      at TOMLParser.goto (C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\parser.js:87:17)
      at TOMLParser.recordEscapeReplacement (C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\toml-parser.js:678:19)
      at TOMLParser.runOne (C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\parser.js:64:30)
      at TOMLParser.returnNow (C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\parser.js:107:17)
      at TOMLParser.parseUnicodeReturn (C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\toml-parser.js:783:21)
      at TOMLParser.runOne (C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\parser.js:64:30)
      at TOMLParser.parse (C:\Users\104104\AppData\Roaming\npm\node_modules\alacritty-themes\node_modules\@iarna\toml\lib\parser.js:45:22) {
    fromTOML: true,
    wrapped: null,
    line: 319,
    col: 15,
    pos: 4793
  },
  code: undefined,
  line: 319,
  col: 15,
  pos: 4793
}
```

Here is the suspect key binding: 

```toml
[[keyboard.bindings]]
chars = "\u001b^?"
key = "Back"
mods = "Alt"
```

### Second problem

I did the fix the error suggested and the `TOML` parser successfully ran but has completely replaced my config with a simple import of the theme.. this is not really ideal since I lost some of my custom settings.. I'm able to add them back under the `import`.. but if I use `alacritty-themes` again, my custom settings are again removed. 

Does `alacritty-themes` not preserve custom configs?

**Comment by rajasegar** [comment]
It should, I think during the yml to toml conversion, there is some bug introduced, will fix it asap and let you folks know

**Comment by rajasegar** [comment]
Pushed a new release 6.0.2 in npm
- Remove the preview option for now since it is buggy, you have to apply the theme to see the changes
- If your old config is not preserved, you can restore them by renaming the latest backup file
  ``` mv alacritty.toml.xxxxxx.bak alacritty.toml```
- Also ensure you remove these sections in your old config file to the new theme to take effect:
  -  [colors.bright]
  - [colors.normal]
  - [colors.primary]

**Comment by Neo-29** [comment]
I tested the new version

No preview of the themes when scrollling...

is it normal?

**Comment by rajasegar** [comment]
@Neo-29 Yes it is intended, since the preview functionality is buggy I turned it off temporarily 
will update this thread once it is fixed
