### ISSUE TITLE
Cannot apply themes

### ISSUE THREAD

**Issue by sharananurag998** [rajasegar/alacritty-themes#3]
Getting this error when I try to apply any theme: -

```
/home/acs/.npm-global/lib/node_modules/alacritty-themes/index.js:22
  const colors = doc.contents.items.filter((i) => i.key.value === "colors")[0];
                              ^

TypeError: Cannot read property 'items' of null
    at updateTheme (/home/acs/.npm-global/lib/node_modules/alacritty-themes/index.js:22:31)
    at /home/acs/.npm-global/lib/node_modules/alacritty-themes/index.js:76:7
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

```

**Comment by rajasegar** [comment]
Hey @sharananurag998 looks like you have nothing configured in your `alacritty.yml`, please uncomment any section or add any new config and check, I will fix this in a patch release.
